### ISSUE TITLE
Description for each tool

### ISSUE THREAD

**Issue by plnox06vv** [emptymonkey/PELT#1]
Hi. Since not everyone of us has an IQ over 90 (for example me), could you please write a description for each tool? Tell us what it does exactly! I've managed to understand one of them and it's quite cool, I'm anxious to learn about the rest.

**Comment by emptymonkey** [comment]
I've given a description for each tool and revamped the overview for PELT. I'll probably refine and edit the page more in the coming days to smooth the wording. Let me know if you think this meets the need of "giving a general overview for someone looking at the tools for the first time". (Having written them all, I forget what it's like not to know them.) Also, thanks for the feedback!

**Comment by plnox06vv** [comment]
Wow... I can't thank you enough. This will be helpful to many. I'll give a review in about 12 hours.

**Comment by plnox06vv** [comment]
Omfg, these tools are extremely malicious. Awesome project, you should add a donation link now before they become more popular. I understood everything.

P.S.
The URL of the project page is wrong in the sigsleeper description.
